### ISSUE TITLE
SVG and DXF from Illustrator

### ISSUE THREAD

**Issue by kasperkamperman** [mondalaci/dxf2svg2kicad#7]
Hi,
I'm trying your tool with Illustrator exports, however they don't seem to work good. I tried different export settings. 

https://dl.dropboxusercontent.com/u/1147392/mandala_quarter_outline.dxf
https://dl.dropboxusercontent.com/u/1147392/mandala_quarter_outline.svg

**Comment by kasperkamperman** [comment]
Opening the DXF in QCAD, doing explode and saving it worked. However it would be nice to not do the QCAD step in between. I tried "expand" (which seems the equivalent of "explode"), however that didn't work either.

**Comment by mondalaci** [comment]
@kasperkamperman It'd be surely nice to leave out the QCAD step but exploding all the different graphics primitives would be fairly time consuming to implement. I'm not sure whether I'll ever have time for this. Given that this is a known issue and it's explicitly mentioned on the user interface I'm closing it.

Regardless, I'm attaching your files to this issue because this way they surely won't vanish and if somebody comes along eventually wanting to fix this issue then he'll have the possibility to do so.

Thanks!

![mandala_quarter_outline dxf](https://cloud.githubusercontent.com/assets/300402/6350346/4ef02a02-bc33-11e4-98fa-e2f3be98cfca.png)
![mandala_quarter_outline svg](https://cloud.githubusercontent.com/assets/300402/6350345/4eeeb42e-bc33-11e4-8b2b-ce642d98744e.png)
