### ISSUE TITLE
Complains that SVG is invalid

### ISSUE THREAD

**Issue by leonerd** [mondalaci/dxf2svg2kicad#8]
I've applied the instructions given (Break Apart) on this SVG and it still complains.
![leonerd_distracted_outline_mono_invpoly_inset really-svg](https://cloud.githubusercontent.com/assets/350941/8365211/890c0d64-1b83-11e5-9361-19e6bc281b3f.png)

**Comment by mondalaci** [comment]
@leonerd I've managed to convert your SVG to KICAD_PCB format. For that, I've updated dxf2svg2kicad to output the correct orientation and more importantly updated the Inkscape instructions of dxf2svg2kicad to cover the cases of more complex drawings like yours.

Rather than giving you the converted file, please check the updated instructions and based on those convert to file youself. This way I'll see whether my instructions are easily reproducible.
